- name: Install ZSH
  ansible.builtin.package: 
    name: "zsh"
    state: present
  become: yes

- name: Install fzf
  ansible.builtin.package: 
    name: "fzf"
    state: present
  become: yes

- name: Install ZSH files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- name: Change user shell to ZSH
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}" 
    shell: /bin/zsh

