- name: Install Swaysome
  kewlfft.aur.aur:
    name: "swaysome"
    state: present
  become: yes
  become_user: aur_builder

- name: Install Swaysome files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['swaysome.service']
