- name: Install k8s dev packages
  ansible.builtin.package:
    name: 
      - "kubectl"
      - "istio"
      - "helm"
    state: present
  become: yes

- name: Install kubectl files 
  ansible.builtin.include_role: 
    name: "fileinstaller"


- name: Install k3d 
  kewlfft.aur.aur: 
    name: "rancher-k3d-bin"
    state: present
  become: yes
  become_user: aur_builder

- name: Install devcontainer cli 
  kewlfft.aur.aur: 
    name: "devcontainer-cli"
    state: present
  become: yes
  become_user: aur_builder
