- name: Install kanshi 
  ansible.builtin.package: 
    name: "kanshi"
    state: present
  become: yes

- name: Install kanshi files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['kanshi.service']
