- name: Install Elephant 
  kewlfft.aur.aur: 
    name:
      - elephant
      - elephant-clipboard
      - elephant-desktopapplications
      - elephant-runner
      - elephant-providerlist
    state: present
  become: yes
  become_user: aur_builder

- name: Install Elephant files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['elephant.service']
