- name: Install Telegram 
  ansible.builtin.package: 
    name: "telegram-desktop"
    state: present
  become: yes

- name: Install telegram files
  ansible.builtin.include_role: 
    name: "fileinstaller"

