- name: Install pulse-autoswitch packages 
  ansible.builtin.package: 
    name: "python-i3ipc"
    state: present
  become: yes

- name: Install python-pulsectl 
  kewlfft.aur.aur: 
    name: "python-pulsectl"
    state: present
  become: yes
  become_user: aur_builder

- name: Install python-pulsectl-asyncio 
  kewlfft.aur.aur: 
    name: "python-pulsectl-asyncio"
    state: present
  become: yes
  become_user: aur_builder

- name: Install pulse-autoswitch files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['pulse-autoswitch.service']
