- name: Install kubectl
  ansible.builtin.package:
    name: 
      - "kubectl"
    state: present
  become: yes

- name: Install kubectl files 
  ansible.builtin.include_role: 
    name: "fileinstaller"
