host_roles:
  - discord 
  - firefox
  - scrollwm
  - slack
  - polkit
  - gnome-keyring
  - k8dev
  - tailscale
  - steam
wayland_scroll_roles:
  - swaysome
  - udiskie
  - walker
  - uwsm
  - nmapplet
  - waybar
  - bluetooth
  - kanshi
  - wlogout
