dotfile_install_base: "{{ansible_env.HOME}}"
dotfile_config_base: "{{[dotfile_install_base, '.config'] | path_join}}"
systemd_user_dir: "{{[dotfile_config_base, 'systemd', 'user'] | path_join}}"
preferred_shell: "zsh"
preferred_terminal: "kitty"
preferred_launcher: "walker"
wayland_use_uwsm: true
scroll_common_roles:
  - swaysome
  - udiskie
  - walker
  - uwsm
  - nmapplet
  - waybar
  - bluetooth
  - wlogout
  - awww
  - mako
  - bluetooth
common_roles:
  - ssh
  - zsh
  - direnv
  - ripgrep
  - lazyvim 
  - lazygit
  - archivers
  - aws-cli
  - jq
  - yq
  - docker
  - telegram
  - pre-commit
  - opentofu


