host_roles:
  - discord
  - firefox
  - scrollwm
  - slack
  - polkit
  - gnome-keyring
  - k8dev
  - tailscale
  - steam
  - brightnessctl
wayland_scroll_roles:
  - swaysome
  - udiskie
  - nmapplet
  - walker
  - uwsm
  - waybar
  - bluetooth
