host_roles:
  - discord
  - firefox
  - scrollwm
  - slack
  - polkit
  - gnome-keyring
  - kubectl
  - tailscale
  - steam
wayland_scroll_roles:
  - swaysome
  - udiskie
  - walker
  - uwsm
  - waybar
