- name: Install bluetooth 
  ansible.builtin.package: 
    name: 
      - "bluez"
      - "bluez-utils"
      - "blueman"
    state: present
  become: yes

- name: Install bluetooth files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['blueman-applet.service']
