- name: Install Udiskie 
  ansible.builtin.package: 
    name: "udiskie"
    state: present
  become: yes

- name: Install Udiskie files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['udiskie.service']
