- name: Install awww
  kewlfft.aur.aur: 
    name:
      - awww-bin 
    state: present
  become: yes
  become_user: aur_builder

- name: Install awww files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- name: Setup systemd wants (awww) for compositor
  ansible.builtin.file:
    src: "{{[systemd_user_dir, 'awww.service'] | path_join }}"
    dest: "{{[systemd_user_dir, compositor_wants, 'awww.service']  | path_join }}"
    state: link
  when: compositor_wants is defined

- name: Setup systemd wants (awww-periodic) for compositor
  ansible.builtin.file:
    src: "{{[systemd_user_dir, 'awww-periodic.service'] | path_join }}"
    dest: "{{[systemd_user_dir, compositor_wants, 'awww-periodic.service']  | path_join }}"
    state: link
  when: compositor_wants is defined
