- name: Install awww
  kewlfft.aur.aur: 
    name:
      - awww-bin 
    state: present
  become: yes
  become_user: aur_builder

- name: Install awww files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['awww.service', 'awww-periodic.service']
