- name: Install tailscale
  ansible.builtin.package:
    name: 
      - "tailscale"
    state: present
  become: yes

- name: Enable tailscale services
  ansible.builtin.systemd_service:
    name: tailscaled 
    enabled: true
    state: started
  become: yes
