- name: Install nm-applet 
  ansible.builtin.package: 
    name: "network-manager-applet"
    state: present
  become: yes

- name: Install nm-applet files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- name: Setup systemd wants for compositor
  ansible.builtin.file:
    src: "{{[systemd_user_dir, 'nm-applet.service'] | path_join }}"
    dest: "{{[systemd_user_dir, compositor_wants, 'nm-applet.service']  | path_join }}"
    state: link
  when: compositor_wants is defined
