- name: Install nm-applet 
  ansible.builtin.package: 
    name: "network-manager-applet"
    state: present
  become: yes

- name: Install nm-applet files
  ansible.builtin.include_role: 
    name: "fileinstaller"

- set_fact:
    uwsm_service_files: ['nm-applet.service']
